### ISSUE TITLE
Docker Compose Services

### ISSUE THREAD

**Issue by smegmarip** [liofal/streamlink#19]
Thanks for making this.
Are we meant to choose one of the two compose services: streamlink or streamlink-latest, or are both required?

**Comment by liofal** [comment]
Hi there. Thanks for the kind words. The purpose of the service “latest” was to tag the image at registry level. Since we switched to the GitHub actions model it’s no longer needed. So I will remove it in the next release. Thanks for pointing that out and sorry for the confusion.  On 27 May 2024, at 22:23, smegmarip ***@***.***> wrote:﻿
Thanks for making this.
Are we meant to choose one of the two compose services: streamlink or streamlink-latest, or are both required?

**Comment by smegmarip** [comment]
Understood and thanks again.
