### ISSUE TITLE
Streamlink Update

### ISSUE THREAD

**Issue by MexTrx** [liofal/streamlink#3]
Any plans on upgrading to Streamlink Version 2.1.1?

**Comment by liofal** [comment]
hi there, which tags of a docker images are you relying on? because every build triggers the setup of the latest pip version available for streamlink

if you rely on version liofal/streamlink:1.8.6, which is also tagged as "latest" you will see that the image Is built as follow:
```
Step 7/14 : RUN pip install --prefix=/install --upgrade streamlink
---> Running in f20a10df14f8
Collecting streamlink
Downloading streamlink-2.1.1-py3-none-any.whl (374 kB)

```

which inside a container will result in the following output

```
/ $ streamlink --version
streamlink 2.1.1
/ $ 
```

any specific feature that 2.1.1 is required for?

**Comment by MexTrx** [comment]
Apologies I mixed up the version numbers. That is the version im looking for.

**Comment by liofal** [comment]
no worries, as a best practice relying on the "latest" tag should always keep the image up-to-date as build is triggered automatically at push on master branch
